export const ontarioSchoolsList = ["AAEC's/e-Learning", "Abbey Park High School", "A B Lucas Secondary School", "ACCESS Program", "Acton District High School", "Adam Scott Collegiate and Vocational Institute", "Adult Day School", "Adult High School", "Agincourt Collegiate Institute", "Ajax High School", "Albert Campbell Collegiate Institute", "Aldershot High School", "Alexander MacKenzie High School", "Alexander Mackenzie Secondary School", "Algoma Education Connection Secondary School", "All Saints Catholic High School", "All Saints Catholic Secondary School Secondary School", "Almaguin Highlands Secondary School", "Almonte District High School", "ALPHA II Alternative School", "Alternative Scarborough Education 1", "Ancaster High School", "Anderson Collegiate and Vocational Institute", "A N Myer Secondary School", "Applewood Acres Secondary School", "Applewood Heights Secondary School", "Archbishop Denis O'Connor Catholic High School", "Arnprior District High School", "Arthur Voaden Secondary School", "Ascension of Our Lord Secondary School", "Assumption Catholic Secondary School", "Assumption College School", "Assumption College School High School", "Athens District High School", "Aurora High School", "Avondale Secondary Alternative School", "Avon Maitland District E-learning Centre", "A Y Jackson Secondary School", "A.Y. Jackson Secondary School", "Banting Memorial High School", "Barrie North Collegiate Institute", "Barrydowne College Senior", "Bayridge Learning Centre", "Bayridge Secondary School", "Bayside Secondary School", "Bayview Secondary School", "B Davison Secondary School Secondary School", "Bear Creek Secondary School", "Beaver Brae Secondary School", "Belle River District High School", "Bell High School", "Bernie Custis Secondary School Secondary School", "Bill Crothers Secondary School", "Bill Hogarth Secondary School", "Birchmount Park Collegiate Institute", "Bishop Alexander Carter Catholic Secondary School", "Bishop Allen Academy Catholic Secondary School", "Bishop Macdonell Catholic Secondary School", "Bishop Marrocco/Thomas Merton Catholic Secondary School", "Bishop Paul Francis Reding Catholic Secondary School", "Bishop Ryan Catholic Secondary School", "Bishop Smith Catholic High School", "Bishop Tonnos Catholic Secondary School", "Blenheim District High School", "Blessed Trinity Catholic Secondary School", "Bloor Collegiate Institute", "Bluevale Collegiate Institute", "Bluewater Alternative Education School", "Bowmanville High School", "Bracebridge and Muskoka Lakes Secondary School", "Bradford District High School", "Bramalea Secondary School", "Brampton Centennial Secondary School", "Brantford Collegiate Institute and Vocational School", "Brebeuf College School", "Brock High School", "Brockville Collegiate Institute", "Brookfield High School", "Brooklin High School", "Bruce Peninsula District School", "Burlington Central High School", "Burnhamthorpe Collegiate Institute", "Bur Oak Secondary School", "Cairine Wilson Secondary School", "CALC Secondary School", "Cameron Heights Collegiate Institute", "Campbellford District High School", "Canterbury High School", "Cardinal Ambrozic Catholic Secondary School", "Cardinal Carter Academy for the Arts", "Cardinal Carter Catholic Secondary School", "Cardinal Leger Secondary School", "Caring and Safe School 1", "Caring and Safe School 2", "Caring and Safe School 3", "Caring and Safe School 4", "Carleton Place High School", "Carrefour Options +", "Castlebrooke Secondary School", "Cathedral High School", "Catholic Central", "Catholic Central High School", "Cawthra Park Secondary School", "Cayuga Secondary School", "Cedarbrae Collegiate Institute", "Centennial Collegiate and Vocational Institute", "Centennial Secondary School", "Central Algoma Secondary School", "Central Elgin Collegiate Institute", "Central Etobicoke High School", "Central Hastings School Secondary School", "Central Huron Secondary School", "Central Peel Secondary School", "Central Technical School", "Central Toronto Academy", "Centre Dufferin District High School", "Centre for Individual Studies Clarington", "Centre for Individual Studies Northumberland", "Centre Wellington District High School", "Chaminade College School", "Chapleau High School", "Charlottenburgh and Lancaster District High School", "Chatham-Kent Secondary School", "Chelmsford Valley District Composite School", "Chinguacousy Secondary School", "Chippewa Secondary School", "Christ the King Catholic Secondary School", "City School", "Clarington Central Secondary School", "Clarke High School", "Clarke Road Secondary School", "Clarkson Secondary School", "Cobourg Collegiate Institute", "Cochrane High School", "College Avenue Secondary School", "Collège français secondaire", "College Heights Secondary School", "Collège Notre-Dame", "Collingwood Collegiate Institute", "Colonel By Secondary School", "Confederation Secondary School", "Contact Alternative School School", "Cornwall Collegiate and Vocational School", "Corpus Christi Catholic Secondary School", "Courtice Secondary School", "Craig Kielburger Secondary School", "Crestwood Secondary School", "Crolancia Secondary School", "C W Jefferys Collegiate Institute", "Danforth Collegiate Institute and Technical School", "Dante Alighieri Academy", "David and Mary Thomson Collegiate Institute", "David Suzuki Secondary School", "Day School -Wellington Centre For ContEd", "Delhi District Secondary School", "Delphi Secondary Alternative School", "Denis Morris Catholic High School", "Donald A Wilson Secondary School", "Don Mills Collegiate Institute", "Downsview Secondary School", "Drewry Secondary School", "Dr. Frank J. Hayden Secondary School", "Dr G W Williams Secondary School", "Dr John M Denison Secondary School", "Dr Norman Bethune Collegiate Institute", "Dryden High School", "DSBN Academy", "Dufferin Centre for Continuing Education", "Dunbarton High School", "Dundas Valley Secondary School", "Dunnville Secondary School", "Durham Alternative Secondary School", "Earl Haig Secondary School", "Earl of March Secondary School", "Eastdale Collegiate and Vocational Institute", "Eastdale Collegiate Institute", "Eastdale Secondary School", "East Elgin Secondary School", "East Northumberland Secondary School", "Eastside Secondary School", "Eastview Secondary School", "Eastwood Collegiate Institute", "East York Alternative Secondary School", "East York Collegiate Institute", "E C Drury/Trillium Demonstration School", "École Cap sur l'Avenir", "École catholique Nouveau Regard", "École publique Centre d'éducation et de formation de", "École secondaire CANO", "École secondaire catholique Algonquin", "École secondaire catholique Ange-Gabriel", "École secondaire catholique Béatrice-Desloges", "École secondaire catholique Champlain", "École secondaire catholique Cité des Jeunes", "École secondaire catholique d'apprentissage virtuel", "École secondaire catholique de Casselman", "École secondaire catholique de La Vérendrye", "École secondaire catholique de l’innovation", "École secondaire catholique de Plantagenet", "École secondaire catholique des satellites", "École secondaire catholique École secondaire de Pain Court", "École secondaire catholique École secondaire Monseigneur-Bruyère", "École secondaire catholique École secondaire Notre-Dame", "École secondaire catholique École secondaire Saint-Dominique-Savio", "École secondaire catholique École secondaire Saint-François-Xavier", "École secondaire catholique E.J.Lajeunesse", "École secondaire catholique Élisabeth-Bruyère", "École secondaire catholique Embrun", "École secondaire catholique Franco-Cité", "École secondaire catholique Franco-Ouest", "École secondaire catholique Garneau", "École secondaire catholique Georges-Vanier", "École secondaire catholique Hearst", "École secondaire catholique Jeanne-Lajoie", "École secondaire catholique Jeunesse-Nord", "École secondaire catholique La Citadelle", "École secondaire catholique L'Alliance", "École secondaire catholique La Renaissance", "École secondaire catholique L'Envol", "École secondaire catholique l’Envolée du Nord", "École secondaire catholique Le Relais", "École secondaire catholique L'Escale", "École secondaire catholique l'Essor", "École secondaire catholique l'Horizon", "École secondaire catholique Mer Bleue", "École secondaire catholique Notre-Dame", "École secondaire catholique Paul-Desmarais", "École secondaire catholique Pierre-Savard", "École secondaire catholique régionale de Hawkesbury", "École secondaire catholique Sainte-Marie", "École secondaire catholique Sainte-Marie-Rivier", "École secondaire catholique Saint-Jean-Baptiste", "École secondaire catholique Saint-Joseph", "École secondaire catholique Samuel-Genest", "École secondaire catholique Ste-Trinité", "École secondaire catholique Thériault", "École secondaire catholique Trillium", "École secondaire Château-Jeunesse", "École secondaire Cité-Supérieure", "École secondaire David Saint-Jacques", "École secondaire de Lamothe-Cadillac", "École secondaire de la Rivière-des-Français", "École secondaire des adultes Le Carrefour", "École secondaire du Sacré-Coeur", "École secondaire Étienne-Brûlé", "École secondaire Franco-Jeunesse", "École secondaire Franco-Niagara", "École secondaire Gabriel-Dumont", "École secondaire Gaétan Gervais", "École secondaire Georges-P-Vanier", "École secondaire Hanmer", "École secondaire Jeunes sans frontières", "École secondaire l'Alliance", "École secondaire Le Caron", "École secondaire l'Orée des Bois", "École secondaire Macdonald-Cartier", "École secondaire Michelle-O'Bonsawin", "École secondaire Norval-Morrisseau", "École secondaire Notre-Dame-du-Sault", "École secondaire Passeport Jeunesse", "École secondaire publique aux Quatre-Vents", "École secondaire publique Campus secondaire l'Héritage", "École secondaire publique De La Salle", "École secondaire publique Echo du Nord", "École secondaire publique Gisèle-Lalonde", "École secondaire publique L'Académie de la Seigneurie", "École secondaire publique L'Alternative", "École secondaire publique L'Équinoxe", "École secondaire publique Le Sommet", "École secondaire publique L'Héritage", "École secondaire publique Louis-Riel", "École secondaire publique Marc-Garneau", "École secondaire publique Maurice-Lapointe", "École secondaire publique Mille-Iles", "École secondaire publique Nipissing Ouest", "École secondaire publique Odyssée", "École secondaire publique Omer-Deslauriers", "École secondaire publique Pierre-de-Blois", "École secondaire publique Rivière-Rideau", "École secondaire publique Rockland", "École secondaire Renaissance", "École secondaire Roméo Dallaire", "École secondaire Ronald-Marion", "École secondaire Toronto Ouest", "École secondaire Villa Française des Jeunes", "Eden High School", "E L Crossley Secondary School", "Elizabeth Wyn Wood Secondary Alternate", "Elliot Lake Secondary School", "Elmira District Secondary School", "Elmvale District High School", "Elsie MacGill Secondary School", "Emery Collegiate Institute", "Emery EdVance Secondary School", "Emily Carr Secondary School", "Englehart High School", "Erie Migration District Secondary School", "Erindale Secondary School", "Erin District High School", "Ernest C Drury School for the Deaf", "Ernestown Secondary School", "ÉSAC Mère-Teresa", "ÉSC de l'Ascension - Vaughan", "ÉSC Monseigneur-de-Charbonnel", "ÉSC Monseigneur-Jamot", "ÉSC Nouvelle-Alliance", "ÉSC Pape-François", "ÉSC Père-Philippe-Lamarche", "ÉSC Père-René-de-Galinée", "ÉSC Renaissance", "ÉSC Saint-Charles-Garnier", "ÉSC Sainte-Famille", "ÉSC Sainte-Trinité", "ÉSC Saint-Frère-André", "ÉSC Saint-Jean-de-Brébeuf", "Espanola High School", "Essex District High School", "Etobicoke Collegiate Institute", "Etobicoke School of the Arts", "Etobicoke Secondary Alternative School", "Father Bressani Catholic High School", "Father Donald MacLellan Catholic Sec Sch Catholic School", "Father Henry Carr Catholic Secondary School", "Father John Redmond Catholic Secondary School", "Father Leo J Austin Catholic Secondary School", "Father Michael Goetz Secondary School", "Father Michael McGivney Catholic High School", "Fellowes High School", "F E Madill Secondary School", "Fenelon Falls Secondary School", "F J Brennan Catholic High School", "F J McElligott Secondary School", "Fletcher's Meadow Secondary School", "Forest Heights Collegiate Institute", "Forest Hill Collegiate Institute", "Fort Frances High School", "Francis Libermann Catholic High School", "Frank Oke Secondary School", "Frederick Banting Secondary Alternate Pr", "Frontenac Secondary School", "Galt Collegiate and Vocational Institute", "Gananoque Secondary School", "Garth Webb Secondary School", "Gary Allan High School - Burlington", "Gary Allan High School - STEP", "G A Wheable Secondary School", "George S Henry Academy", "Georges Vanier Secondary School", "Georgetown District High School", "Georgian Bay Community School Secondary School", "Georgian Bay District Secondary School", "Geraldton Composite School", "Glebe Collegiate Institute", "Glencoe District High School", "Glendale High School", "Glendale Secondary School", "Glenforest Secondary School", "Glengarry District High School", "Glenview Park Secondary School", "Gloucester High School", "G L Roberts Collegiate and Vocational Institute", "Goderich District Collegiate Institute", "Governor Simcoe Secondary School", "Grand Erie Learning Alternatives", "Grand River Collegiate Institute", "Granite Ridge Education Centre Secondary School", "Gravenhurst High School", "Greater Fort Erie Secondary School", "Great Lakes Secondary School", "Greenwood Secondary School", "Grey Highlands Secondary School", "Guelph Collegiate and Vocational Institute", "Hagersville Secondary School", "Haliburton Highland Secondary School", "Hammarskjold High School", "Harbord Collegiate Institute", "Harold M. Brathwaite Secondary School", "H B Beal Secondary School", "Hearst High School", "Heart Lake Secondary School", "Henry Street High School", "Heydon Park Secondary School", "Hillcrest High School", "Hill Park System Alternative Education", "Hodan Nalayeh Secondary School", "Holy Cross Catholic Academy High School", "Holy Cross Catholic Secondary School", "Holy Name of Mary Secondary School", "Holy Names Catholic High School", "Holy Trinity Catholic High School", "Holy Trinity Catholic Secondary School", "Hon W C Kennedy Collegiate Institute", "Hornepayne High School", "Humberside Collegiate Institute", "Humberview Secondary School", "Huntsville High School", "Huron Heights Secondary School", "Huron Park Secondary School", "I E Weldon Secondary School", "Ignace Secondary School", "Immaculata High School", "Ingersoll District Collegiate Institute", "Inglenook Community School", "Innisdale Secondary School", "Iona Secondary School", "Iroquois Falls Secondary School", "Iroquois Ridge High School", "Jacob Hespeler Secondary School", "James Cardinal McGuigan Catholic High School", "James Street Alternative Education", "Jarvis Collegiate Institute", "J Clarke Richardson Collegiate Institute", "Jean Augustine Secondary School", "John Cabot Catholic Secondary School", "John Diefenbaker Senior School", "John Fraser Secondary School", "John F Ross Collegiate and Vocational Institute", "John McCrae Secondary School", "John McGregor Secondary School", "John Paul II Catholic Secondary School", "John Polanyi Collegiate Institute", "Judith Nyman Secondary School", "Kapapamahchakwew - Wandering Spirit Scho", "Kapuskasing District High School", "Katarokwi Learning Centre", "Kenner Collegiate and Vocational Institute", "Keswick High School", "Kincardine District Secondary School", "King City Secondary School", "Kingston Secondary School", "Kipling Collegiate Institute", "Kirkland Lake District Composite Secondary School", "Kitchener Waterloo Collegiate and Vocational School", "Korah Collegiate and Vocational School", "Lakehead Alternative School", "Lakeshore Catholic High School", "Lakeshore Collegiate Institute", "Lake Superior High School", "Lambton Central Collegiate and Vocational Institute", "Lambton Kent Composite School", "L'Amoreaux Collegiate Institute", "Langstaff Secondary School", "Lasalle Secondary School", "La Salle Secondary School", "Launch Secondary School", "Laura Secord Secondary School", "Laurel Heights Secondary School", "Lawrence Park Collegiate Institute", "LDCSB Online School High School", "Leamington District Secondary School", "Leaside High School", "Lester B Pearson Catholic High School", "Lester B Pearson Collegiate Institute", "Lifetime Learning Centre Secondary School", "Limestone Online Secondary School", "Limestone School of Community Education", "Lincoln M. Alexander Secondary School", "Lindsay Collegiate and Vocational Institute", "Lisgar Collegiate Institute", "Listowel District Secondary School", "Lively District Secondary School", "Lockerby Composite School", "Lo-Ellen Park Secondary School", "London Central Secondary School", "London South Collegiate Institute", "Longfields Davidson Heights Secondary School", "Lord Dorchester Secondary School", "Loretto Abbey Catholic Secondary School", "Loretto College School", "Lorne Park Secondary School", "Louise Arbour Secondary School", "Loyalist Collegiate and Vocational Institute", "Loyola Catholic Secondary School", "Loyola Community Learning Centre", "Mackenzie Community School - Secondary School", "Madawaska Valley District School - Secondary District High School", "Madonna Catholic Secondary School", "Malvern Collegiate Institute", "Manitoulin Secondary School", "Manitouwadge High School", "Maple High School", "Maple Ridge Secondary School", "Maplewood High School", "Maplewood Secondary School", "Marathon High School", "Marc Garneau Collegiate Institute", "Markham District High School", "Markville Secondary School", "Marshall McLuhan Catholic Secondary School", "Martingrove Collegiate Institute", "Marymount Academy Catholic School", "Mary Ward Catholic Secondary School", "Maxwell Heights Secondary School", "Mayfield Secondary School", "McKinnon Park Secondary School", "Meadowvale Secondary School", "Medway High School", "Merivale High School", "Michael Power/St Joseph High School", "Michipicoten High School", "Middlefield Collegiate Institute", "Milliken Mills High School", "Milton District High School", "Mississauga Secondary School", "Mitchell District High School", "M M Robinson High School", "Monarch Park Collegiate Institute", "Monsignor Doyle Catholic Secondary School", "Monsignor John Pereyma Catholic Secondary School", "Monsignor Paul Dwyer Catholic High School", "Monsignor Percy Johnson Catholic High School", "Montcalm Secondary School", "Mother Teresa Catholic Secondary School", "Msgr Fraser College", "Msgr Fraser-Midland", "Msgr Fraser Orientation Centre", "Nantyr Shores Secondary School", "Napanee District Secondary School", "Native Learning Centre", "Native Learning Centre East", "Neil McNeil High School", "Nelson High School", "Nepean High School", "Newmarket High School", "Newtonbrook Secondary School", "Niagara Catholic Online Secondary School", "Niagara Catholic Virtual Secondary School", "Nicholson Catholic College", "Nipigon Red Rock District High School", "Nora Frances Henderson", "Norman Johnston Secondary Alternate Prog", "North Addington Education Centre", "North Albion Collegiate Institute", "North Dundas District High School", "North East Secondary Alternative School", "Northern Collegiate Institute and Vocational School", "Northern Lakes High School", "Northern Lights Secondary School", "Northern Secondary School", "North Grenville District High School", "North Hastings High School", "North Lambton Secondary School", "North Middlesex District High School", "North Park Collegiate and Vocational School", "North Park Secondary School", "North Shore Adolescent Education School", "North Star High School", "North Toronto Collegiate Institute", "Northview Heights Secondary School", "North West Secondary Alternative School", "Norwell District Secondary School", "Norwood District High School", "Notre Dame Catholic High School", "Notre Dame Catholic Secondary School", "Notre Dame College School", "Notre Dame High School", "Nottawasaga Pines Secondary School", "N'Swakamok Native Alternative School", "Oakridge Secondary School", "Oakville Trafalgar High School", "Oakwood Collegiate Institute", "Oasis Alternative Secondary School", "OCSB Achievement Centre", "O'Gorman High School", "O'Neill Collegiate and Vocational Institute", "Opeongo High School", "Orangeville District Secondary School", "Orchard Park Secondary School", "Orillia Secondary School", "Osgoode Township High School", "Ottawa Technical Secondary School", "Our Lady of Lourdes Catholic School", "Our Lady of Mount Carmel Secondary School", "Our Lady of the Bay Catholic High School", "Our Lady of the Lake Catholic Academy High School", "Our Lady Queen of the World CA High School", "Owen Sound District Secondary School Secondary School", "PACE", "Paris District High School", "Parkdale Collegiate Institute", "Parkholme Secondary School", "Parkside Collegiate Institute", "Parkview Alternative School", "Parry Sound High School", "Patrick Fogarty Catholic Secondary School", "Pauline Johnson Collegiate and Vocational School", "Peel Alternative North", "Peel Alternative North ISR", "Peel Alternative South", "Peel Alternative South ISR", "Peel eLearning/OeLC Secondary School", "Peninsula Shores District School", "Perth and District Collegiate Institute", "Peterborough Collegiate and Vocational School", "Philip Pocock Catholic Secondary School", "Pickering High School", "Pierre Elliott Trudeau High School", "Pine Ridge Secondary School", "Pope Francis Catholic Secondary School", "Port Colborne High School", "Port Credit Secondary School", "Port Hope High School", "Port Perry High School", "Preston High School", "Prince Edward Collegiate Institute", "PVNC Online Catholic School", "Rainy River High School", "Rebecca Street Alternative Education Secondary School", "Red Lake District High School", "Regina Mundi College", "Regiopolis/Notre-Dame Catholic High School", "Renfrew Collegiate Institute", "Renfrew County Adult Day School", "Resurrection Catholic Secondary School", "R H King Academy", "Richard Pfaff Secondary Alternate Site", "Richmond Green Secondary School", "Richmond Hill High School", "Richview Collegiate Institute", "Rick Hansen Secondary School", "Rideau District High School", "Ridgemont High School", "Ridgetown District High School", "Riverdale Collegiate Institute", "Riverside Secondary School", "Riverside South Secondary School", "Robarts/Amethyst Demonstration Secondary School", "Robarts Provincial School for the Deaf", "Robert F Hall Catholic Secondary School", "Rockland District High School", "Roland Michener Secondary School", "Rosedale Heights School of the Arts", "Rosemount - U Turn School", "R S Mclaughlin Collegiate and Vocational Institute", "Runnymede Collegiate Institute", "Russell High School", "Sacred Heart Catholic High School", "Sacred Heart High School", "Saint Francis Catholic Secondary School", "Saint Kateri Tekakwitha Catholic Secondary School", "Saint Michael Catholic High School", "Saint Paul Catholic High School", "Saltfleet High School", "Sandalwood Heights Secondary School", "Sandwich Secondary School", "SATEC @ W A Porter Collegiate Institute", "Saugeen District Secondary School", "Saunders Secondary School", "Scarborough Centre for Alternative Studi", "School of Experiential Education", "School of Life Experience", "Seaway District High School", "SEED Alternative School", "Senator O'Connor College School", "Sherwood Secondary School", "Silverthorn Collegiate Institute", "Simcoe Composite School", "Simcoe Shores Secondary School", "Sinclair Secondary School", "Sioux North High School", "Sir Allan MacNab Secondary School", "Sir Frederick Banting Secondary School", "Sir Guy Carleton Secondary School", "Sir James Whitney/Sagonaska Secondary School", "Sir James Whitney School for the Deaf", "Sir John A Macdonald Collegiate Institute", "Sir Oliver Mowat Collegiate Institute", "Sir Robert Borden High School", "Sir Wilfrid Laurier Collegiate Institute", "Sir Wilfrid Laurier Secondary School", "Sir William Mulock Secondary School", "Sir William Osler High School", "Sir Winston Churchill Secondary School", "Smiths Falls District Collegiate Institute", "South Carleton High School", "South East Secondary Alternative School", "South Grenville District High School", "South Huron District High School", "Southwood Secondary School", "St Aloysius Gonzaga Secondary School", "Stamford Collegiate", "St. Andre Bessette Secondary School", "St Anne's Catholic Secondary School", "St Anne Secondary School", "St Augustine Catholic High School", "St Augustine Secondary School", "Stayner Collegiate Institute", "St Basil-the-Great College School", "St Benedict Catholic Secondary School", "St Brother André Catholic High School", "St Catharines Collegiate Institute and Vocational School", "St. Charles Catholic Adult Secondary School", "St Charles College", "St David Catholic Secondary School", "St Dominic Catholic Secondary School", "St Don Bosco Catholic Secondary School", "St Edmund Campion Secondary School", "St Elizabeth Catholic High School", "Stephen Leacock Collegiate Institute", "Stephen Lewis Secondary School", "St. Francis Xavier Catholic School", "St Francis Xavier Catholic High School", "St. Francis Xavier Catholic Secondary School", "St Francis Xavier Secondary School", "St Ignatius High School", "St. Ignatius of Loyola Catholic Secondary School", "St. James Catholic Education Centre High School", "St James Catholic School", "St Jean de Brebeuf Catholic High School", "St. Jean de Brebeuf Catholic Secondary School", "St Joan of Arc Catholic Academy", "St Joan of Arc Catholic High School", "St. Joan of Arc Catholic Secondary School", "St Joan of Arc High School", "St John Bosco Catholic School", "St John Catholic High School", "St John Henry Newman Catholic High School", "St. John Henry Newman Catholic Secondary School", "St John Paul II Catholic Secondary School", "St John's College", "St Joseph High School", "St Joseph Morrow Park Catholic Secondary School", "St Joseph-Scollard Hall Secondary School", "St Joseph's College School", "St Joseph Secondary School", "St Joseph's High School", "St Joseph's Secondary School", "St Joseph's Separate School", "St. Kateri Tekakwitha Catholic Secondary Catholic School", "St Lawrence Secondary School", "St. Luke Catholic High School", "St Luke Learning Centre", "St Marcellinus Secondary School", "St Marguerite d'Youville Secondary School", "St Mark High School", "St Martin Catholic School", "St Martin Secondary School", "St Mary Catholic Academy", "St. Mary Catholic Learning Centre", "St. Mary Catholic Learning Centre Day", "St Mary Catholic Secondary School", "St. Mary Catholic Secondary School", "St Mary's College Separate School", "St Marys D.C. &amp; V. I. High School", "St Mary's High School", "St Matthew Catholic Secondary School", "St Matthew High School", "St Maximilian Kolbe High School", "St Michael Catholic Secondary School", "St. Michael Catholic Secondary School", "St Michael High School", "St. Michael's Adult High School", "St Michael's Choir School", "St Mother Teresa Catholic Academy", "St. Mother Teresa High School", "St Nicholas Adult High School", "St Oscar Romero Catholic Secondary School", "St. Oscar Romero School", "Stouffville District Secondary School", "St Patrick Catholic Secondary School", "St Patrick High School", "St Patrick's Catholic High School", "St Patrick's High School", "St Paul Catholic Secondary School", "St Paul High School", "St Paul Secondary School", "St. Peter Catholic Secondary School", "St Peter High School", "St Peter's Secondary School", "St Pius X High School", "Stratford District Secondary School", "Strathroy District Collegiate Institute", "Streetsville Secondary School", "St Robert Catholic High School", "St. Roch Catholic Secondary School", "St. Stephen Catholic Secondary School", "St Theresa Catholic Secondary School", "St Theresa of Lisieux Catholic High School", "St Theresa's Separate School", "St. Thomas Aquinas Catholic High School", "St Thomas Aquinas Catholic Secondary School", "St. Thomas Aquinas Catholic Secondary School", "St Thomas Aquinas High School", "St Thomas Aquinas Secondary School", "St. Thomas More Catholic Secondary School", "St Thomas of Villanova Secondary School", "Subway Academy I", "Subway Academy II", "Sudbury Secondary School", "Superior Collegiate and Vocational Institute", "Superior Heights Collegiate and Vocational School", "Sutton District High School", "Sydenham High School", "Tagwi Secondary School", "TB Catholic Alternative Education", "Tecumseh Vista Academy- Secondary", "Thames Valley Alternative Secondary School", "The Student School", "The Woodlands Secondary School", "Thistletown Collegiate Institute", "Thomas A Blakelock High School", "Thomas A Stewart Secondary School", "Thomas Merton Catholic Secondary School", "Thomas Merton Online Catholic School", "Thornhill Secondary School", "Thornlea Secondary School", "Thorold Secondary School", "Thousand Islands Secondary School", "Tilbury District High School", "Timiskaming District Secondary School", "Timmins High and Vocational School", "T. L. Kennedy Secondary School", "Tollgate Technological Skills Centre Secondary School", "Tommy Douglas Secondary School", "Trenton High School", "T R Leger School of Adult &amp; Continuing Secondary School", "Turner Fenton Secondary School", "Turning Point Alternative Education School", "Twin Lakes Secondary School", "UGDSB Online Learning Program", "Unionville High School", "Urban Aboriginal Alternate High School", "Ursula Franklin Academy", "Ursuline College Chatham Catholic Secondary School", "Uxbridge Secondary School", "Valley Heights Secondary School", "Valour JK to 12 School - Secondary School", "Vankleek Hill Collegiate Institute", "Victoria Park Collegiate Institute", "Vincent Massey Secondary School", "Walkerton District Community School", "Walkerville Collegiate Institute", "Wallaceburg District Secondary School", "Waterdown District High School", "Waterford District High School", "Waterloo Collegiate Institute", "Waterloo-Oxford District Secondary School", "W C Eaket Secondary School", "Welland Centennial Secondary School", "Wellington Catholic Online School", "Wellington Heights Secondary School", "West Carleton Secondary School", "West Credit Secondary School", "Westdale Secondary School", "West Elgin Secondary School", "West End Alternative School", "Western Technical &amp; Commercial School", "West Ferris Secondary School", "Westgate Collegiate and Vocational Institute", "West Hill Collegiate Institute", "West Humber Collegiate Institute", "Westlane Secondary School", "Westminster Secondary School", "Westmount Collegiate Institute", "Westmount Secondary School", "West Niagara Secondary School", "Weston Collegiate Institute", "Westside Secondary School", "Westview Centennial Secondary School", "Westview Freedom Academy Secondary School", "Wexford Collegiate School for the Arts", "W. F. Herman Academy Secondary School", "White Oaks High School", "White Pines Collegiate and Vocational School", "William Lyon Mackenzie Collegiate Institute", "Windsor Public Alternative Secondary School", "Winston Churchill Collegiate Institute", "Woburn Collegiate Institute", "Woodbridge College", "Woodroffe High School", "Woodstock Collegiate Institute", "W Ross Macdonald Deaf Blind Secondary School", "W Ross Macdonald Provincial Secondary School", "Yorkdale Secondary School", "York Humber High School", "York Memorial Collegiate Institute", "York Mills Collegiate Institute", "Other"];
export const ontarioCitiesList = [
    "Addington Highlands",
    "Adelaide-Metcalfe",
    "Adjala-Tosorontio",
    "Admaston/Bromley",
    "Ajax",
    "Alfred and Plantagenet",
    "Algonquin Highlands",
    "Alnwick/Haldimand",
    "Alvinston",
    "Amaranth",
    "Amherstburg",
    "Armour",
    "Armstrong",
    "Arnprior",
    "Arran-Elderslie",
    "Ashfield-Colborne-Wawanosh",
    "Asphodel-Norwood",
    "Assiginack",
    "Athens",
    "Atikokan",
    "Augusta",
    "Aurora",
    "Aylmer",
    "Bancroft",
    "Barrie",
    "Bayfield",
    "Bayham",
    "Beachburg",
    "Beckwith",
    "Belleville",
    "Black River-Matheson",
    "Blandford-Blenheim",
    "Blind River",
    "Bluewater",
    "Bonfield",
    "Bonnechere Valley",
    "Bracebridge",
    "Bradford West Gwillimbury",
    "Brampton",
    "Brant",
    "Brantford",
    "Breslau",
    "Brighton",
    "Brock",
    "Brockton",
    "Brockville",
    "Brudenell, Lyndoch and Raglan",
    "Burford",
    "Burlington",
    "Caledon",
    "Callander",
    "Cambridge",
    "Carleton Place",
    "Carling",
    "Casselman",
    "Cavan Monaghan",
    "Central Elgin",
    "Central Frontenac",
    "Central Huron",
    "Central Manitoulin",
    "Centre Hastings",
    "Centre Wellington",
    "Champlain",
    "Chapleau",
    "Chatham",
    "Chatsworth",
    "Chisholm",
    "Claremont",
    "Clarence-Rockland",
    "Clarington",
    "Clearview",
    "Cobalt",
    "Cobourg",
    "Cochrane",
    "Collingwood",
    "Conestogo",
    "Cornwall",
    "Cramahe",
    "Dawn-Euphemia",
    "Deep River",
    "Deseronto",
    "Douro-Dummer",
    "Drummond/North Elmsley",
    "Dryden",
    "Dutton/Dunwich",
    "Dysart et al",
    "East Ferris",
    "East Garafraxa",
    "East Gwillimbury",
    "East Hawkesbury",
    "East Zorra-Tavistock",
    "Edwardsburgh/Cardinal",
    "Elizabethtown-Kitley",
    "Elliot Lake",
    "Emo",
    "Englehart",
    "Enniskillen",
    "Erin",
    "Espanola",
    "Essa",
    "Essex",
    "Faraday",
    "Fort Erie",
    "Fort Frances",
    "French River / Rivière des Français",
    "Front of Yonge",
    "Frontenac Islands",
    "Gananoque",
    "Georgian Bay",
    "Georgian Bluffs",
    "Georgina",
    "Goderich",
    "Grand Valley",
    "Gravenhurst",
    "Greater Madawaska",
    "Greater Napanee",
    "Greenstone",
    "Grey Highlands",
    "Grimsby",
    "Guelph",
    "Guelph/Eramosa",
    "Halton Hills",
    "Hamilton",
    "Hamilton Township",
    "Hanover",
    "Hastings Highlands",
    "Havelock-Belmont-Methuen",
    "Hawkesbury",
    "Hearst",
    "Hensall",
    "Highlands East",
    "Hillsburgh",
    "Hindon Hill",
    "Horton",
    "Howick",
    "Huntsville",
    "Huron East",
    "Huron Shores",
    "Huron-Kinloss",
    "Ignace",
    "Ingersoll",
    "Innisfil",
    "Iroquois Falls",
    "Kapuskasing",
    "Kawartha Lakes",
    "Kenora",
    "Killaloe, Hagarty and Richards",
    "Kincardine",
    "King",
    "Kingsville",
    "Kirkland Lake",
    "Kitchener",
    "Komoka",
    "Laird",
    "Lake of Bays",
    "Lakeshore",
    "Lambton Shores",
    "Lanark Highlands",
    "Lappe",
    "LaSalle",
    "Laurentian Hills",
    "Laurentian Valley",
    "Leamington",
    "Leeds and the Thousand Islands",
    "Lincoln",
    "London",
    "Loyalist",
    "Lucan Biddulph",
    "Macdonald, Meredith and Aberdeen Additional",
    "Madawaska Valley",
    "Madoc",
    "Magnetawan",
    "Malahide",
    "Manitouwadge",
    "Mapleton",
    "Marathon",
    "Markham",
    "Markstay",
    "Marmora and Lake",
    "Mattawa",
    "McDougall",
    "McKellar",
    "McNab/Braeside",
    "Meaford",
    "Melancthon",
    "Merrickville",
    "Middlesex Centre",
    "Midland",
    "Milton",
    "Minto",
    "Mississauga",
    "Mississippi Mills",
    "Mono",
    "Montague",
    "Moonbeam",
    "Moosonee",
    "Morris-Turnberry",
    "Mulmur",
    "Muskoka Falls",
    "Neebing",
    "New Tecumseth",
    "Newmarket",
    "Niagara Falls",
    "Niagara-on-the-Lake",
    "Nipigon",
    "Nipissing",
    "North Algona Wilberforce",
    "North Bay",
    "North Dumfries",
    "North Dundas",
    "North Frontenac",
    "North Glengarry",
    "North Grenville",
    "North Huron",
    "North Kawartha",
    "North Middlesex",
    "North Perth",
    "North Stormont",
    "Northeastern Manitoulin and the Islands",
    "Northern Bruce Peninsula",
    "Norwich",
    "Oakville",
    "Oliver Paipoonge",
    "Orangeville",
    "Orillia",
    "Oro-Medonte",
    "Oshawa",
    "Otonabee-South Monaghan",
    "Ottawa",
    "Owen Sound",
    "Papineau-Cameron",
    "Parry Sound",
    "Pelham",
    "Pembroke",
    "Penetanguishene",
    "Perry",
    "Perth",
    "Perth East",
    "Perth South",
    "Petawawa",
    "Peterborough",
    "Petrolia",
    "Pickering",
    "Plantagenet",
    "Plympton-Wyoming",
    "Point Edward",
    "Port Colborne",
    "Port Hope",
    "Powassan",
    "Prescott",
    "Prince",
    "Puslinch",
    "Quinte West",
    "Ramara",
    "Red Lake",
    "Renfrew",
    "Richmond Hill",
    "Rideau Lakes",
    "Russell",
    "Sables-Spanish Rivers",
    "Sagamok",
    "Sarnia",
    "Saugeen Shores",
    "Sault Ste. Marie",
    "Schreiber",
    "Scugog",
    "Seguin",
    "Selwyn",
    "Severn",
    "Shelburne",
    "Shuniah",
    "Sioux Lookout",
    "Sioux Narrows-Nestor Falls",
    "Smiths Falls",
    "Smooth Rock Falls",
    "South Algonquin",
    "South Bruce",
    "South Bruce Peninsula",
    "South Dundas",
    "South Frontenac",
    "South Glengarry",
    "South Huron",
    "South River",
    "South Stormont",
    "South-West Oxford",
    "Southgate",
    "Southwest Middlesex",
    "Southwold",
    "Springwater",
    "St. Catharines",
    "St. Clair",
    "St. Joseph",
    "St. Marys",
    "St. Thomas",
    "St.-Charles",
    "Stirling-Rawdon",
    "Stone Mills",
    "Stouffville",
    "Stratford",
    "Strathroy-Caradoc",
    "Strong",
    "Sudbury",
    "Tara",
    "Tay",
    "Tay Valley",
    "Tecumseh",
    "Temiskaming Shores",
    "Terrace Bay",
    "Thames Centre",
    "The Blue Mountains",
    "The Nation / La Nation",
    "Thessalon",
    "Thorold",
    "Thunder Bay",
    "Tillsonburg",
    "Timmins",
    "Tiny",
    "Toronto",
    "Trent Hills",
    "Trent Lakes",
    "Tweed",
    "Tyendinaga",
    "Uxbridge",
    "Vaughan",
    "Wainfleet",
    "Warwick",
    "Wasaga Beach",
    "Waterloo",
    "Wawa",
    "Welland",
    "Wellesley",
    "Wellington",
    "Wellington North",
    "West Elgin",
    "West Grey",
    "West Lincoln",
    "West Nipissing / Nipissing Ouest",
    "West Perth",
    "Whitby",
    "Whitewater Region",
    "Wilmot",
    "Windsor",
    "Woodstock",
    "Woolwich",
    "Zorra",
    "Other",
];
export const dietaryRestrictionsList = [
    "Lactose Intolerant",
    "Halal",
    "Vegetarian",
    "Vegan",
    "Gluten Free",
    "Other"
];